apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-springboot3-logging
spec:
  storageClassName: nutanix-files-dynamic-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
