apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot3-logging
  labels:
    app: springboot3-logging
    env: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot3-logging
      env: testing
  template:
    metadata:
      name: springboot3-logging
      labels:
        app: springboot3-logging
        env: testing
    spec:
      hostAliases:
        - hostnames:
            - logging-apps.logging.bank-muamalat.com
          ip: 10.55.22.48
      containers:
        - name: springboot3-logging
          image: dimmaryanto93/com.maryanto.dimas.example-springboot3-logging-file:v1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /var/logs/springboot-app
              name: logging-path
      volumes:
        - name: logging-path
          persistentVolumeClaim:
            claimName: pvc-springboot3-logging
            readOnly: false
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      hostAliases:
        - hostnames:
            - logging-apps.logging.bank-muamalat.com
          ip: 10.55.22.48
      containers:
        - name: nginx
          image: nginx:mainline
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /var/logs/springboot-app
              name: logging-path
      restartPolicy: Always
      volumes:
        - name: logging-path
          persistentVolumeClaim:
            claimName: pvc-springboot3-logging
            readOnly: true
