apiVersion: v1
kind: Service
metadata:
  name: springboot3-logging
spec:
  selector:
    app: springboot3-logging
    env: testing
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort