apiVersion: v1
kind: PersistentVolume
metadata:
  name: springboot-log-storage
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /logging-apps/spring1-app
    server: 10.55.22.48