apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: springboot-log-storage
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  volumeMode: Filesystem
  volumeName: springboot-log-storage
