---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: springboot-log-storage
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver:
    volumeHandle: