apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-springboot3-logging
spec:
  storageClassName: nutanix-s3-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  volumeMode: Filesystem
